### ISSUE TITLE
Getting Failed to load program Error

### ISSUE THREAD

**Issue by ziggahunhow** [solana-labs/break#377]
Hi, 

I've just started out to play with Solana, and I'm trying to run the server with a local cluster. The cluster and server was started successfully; however, I encountered this error in the server after a few minutes.

```
Failed to load program Error: Transaction was not confirmed in 60.22 seconds (null)
    at _callee$ (/Users/peterlin/Downloads/break/server/node_modules/@solana/web3.js/src/util/send-and-confirm-transaction.js:49:9)
    at tryCatch (/Users/peterlin/Downloads/break/server/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/peterlin/Downloads/break/server/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/peterlin/Downloads/break/server/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/peterlin/Downloads/break/server/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/peterlin/Downloads/break/server/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to load program Error:
    at new StructError (/Users/peterlin/Downloads/break/server/node_modules/superstruct/src/struct-error.ts:37:18)
    at Function.assert (/Users/peterlin/Downloads/break/server/node_modules/superstruct/src/struct.ts:55:13)
    at GetParsedAccountInfoResult (/Users/peterlin/Downloads/break/server/node_modules/superstruct/src/struct.ts:31:46)
    at Connection._callee15$ (/Users/peterlin/Downloads/break/server/node_modules/@solana/web3.js/src/connection.js:1803:17)
    at tryCatch (/Users/peterlin/Downloads/break/server/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/peterlin/Downloads/break/server/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/peterlin/Downloads/break/server/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/peterlin/Downloads/break/server/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/peterlin/Downloads/break/server/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>) {
  type: '{jsonrpc,id,error} | {jsonrpc,id,error,result}',
  value: {
    jsonrpc: '2.0',
    result: { context: [Object], value: [Object] },
    id: '81e26836-ff7f-4e24-9ee8-30aad7a71cf8'
  },
  path: [],
  branch: [
    {
      jsonrpc: '2.0',
      result: [Object],
      id: '81e26836-ff7f-4e24-9ee8-30aad7a71cf8'
    }
  ],
  failures: [
    {
      value: [Object],
      branch: [Array],
      path: [],
      type: '{jsonrpc,id,error} | {jsonrpc,id,error,result}'
    }
  ]
}
```

**Comment by jstarry** [comment]
@ziggahunhow sorry for the delay! Can you share more details? What cluster were you trying to load the program on? What version of web3 is listed in the `package-lock.json`?

**Comment by jstarry** [comment]
Feel free to re-open if you're having this issue.
